sudo: required

services:
  - docker

jobs:
  include:
    - stage: base images
      if: branch = master AND type != pull_request
      script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && script/distribute-docker-base-mkl
    - if: branch = master AND type != pull_request
      script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && script/distribute-docker-base-gpu

    - stage: all other images
      if: branch = master AND type != pull_request
      script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && script/distribute-docker-tensorflow
    - if: branch = master AND type != pull_request
      script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && script/distribute-docker-tensorflow-optimized
    - if: branch = master AND type != pull_request
      script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && script/distribute-docker-tensorflow-serving
