#!/usr/bin/env bash
set -e
source script/docker_build_and_push.sh
GOOGLE_TENSORFLOW_SERVING_VERSION=1.7.0
BINARIES_TENSORFLOW_SERVING_VERSION=1.7.0
set -x

docker_build_and_push triage/python2.7-tensorflow-serving:$GOOGLE_TENSORFLOW_SERVING_VERSION tensorflow-serving/python2.7-tensorflow-serving.Dockerfile "--build-arg TENSORFLOW_SERVING_VERSION=$GOOGLE_TENSORFLOW_SERVING_VERSION"
docker_build_and_push triage/python2.7-tensorflow-serving-optimized:$BINARIES_TENSORFLOW_SERVING_VERSION tensorflow-serving/python2.7-tensorflow-serving-optimized.Dockerfile "--build-arg TENSORFLOW_SERVING_VERSION=$BINARIES_TENSORFLOW_SERVING_VERSION"

docker_build_and_push triage/python2.7-tensorflow-serving-gpu:$BINARIES_TENSORFLOW_SERVING_VERSION tensorflow-serving/python2.7-tensorflow-serving-gpu.Dockerfile "--build-arg TENSORFLOW_SERVING_VERSION=$BINARIES_TENSORFLOW_SERVING_VERSION"
docker_build_and_push triage/python2.7-tensorflow-serving-optimized-gpu:$BINARIES_TENSORFLOW_SERVING_VERSION tensorflow-serving/python2.7-tensorflow-serving-optimized-gpu.Dockerfile "--build-arg TENSORFLOW_SERVING_VERSION=$BINARIES_TENSORFLOW_SERVING_VERSION"
